### ISSUE TITLE
System Tests for EI

### ISSUE THREAD

**Issue by roos-ericsson** [eiffel-community/eiffel-intelligence-frontend#162]
### Description
As a developer I want to have System Tests for EI so that I can more confidently make changes in the code without breaking anything in a live environment.

We need to adapt the integration tests to work against instances of EI back-ends in another eiffel domain or in another place. This means that the test will not start the instances of EI back-end.

The code for testing the back-ends will be placed in repository for front-end.

The same system tests will be run for three of our existing default back-ends (artifact, test execution and source changed) and the steps will be as follows, common for each tested back-end.

* Create configurations for all the back-ends to be tested and provide it as environment variable but also as a file.
* Create subscriptions specific to the tested back-end
* Create jobs that will send events specific to rules for each back-end trigger the jobs
* Loop to see if all the jobs have been successful

#### Artifact Rules
![artifactrules](https://user-images.githubusercontent.com/24456185/52562470-e6490900-2dfe-11e9-83d5-edfacad47538.png)

#### Source Change Rules
![sourcechangerules](https://user-images.githubusercontent.com/24456185/52562471-e6e19f80-2dfe-11e9-908e-171fe41c04de.png)

#### Test Execution Rules
![test-executionrules](https://user-images.githubusercontent.com/24456185/52562472-e6e19f80-2dfe-11e9-9ee0-37c8c2da7b47.png)

### Definition of Done
This issues contains several sub-issues that must be completed before this issue is considered done. 
Sub-issues:
- [x] #164 
- [x] #165 
- [x] #172 
- [x] #173 
- [x] #180 
- [x] #182 
- [x] #190

**Comment by e-pettersson-ericsson** [comment]
Closing this issue, since all the issues below have been adressed and resolved.
