### ISSUE TITLE
Artifact Jobs have Successfully Triggered

### ISSUE THREAD

**Issue by roos-ericsson** [eiffel-community/eiffel-intelligence-frontend#164]
### Description
As a system test designer I want to check that artifact jobs have successfully triggered and then remove the subscriptions and jobs so that the system test environment is cleaned after the system tests. 

- [ ] Loop for some time to see artifact jobs successfully triggered.
- [ ] Remove subscriptions and jobs.

Part of #162

**Comment by e-pettersson-ericsson** [comment]
Closing this issue since code changes have been merged.
