### ISSUE TITLE
Subscription for Source Change Back-end

### ISSUE THREAD

**Issue by roos-ericsson** [eiffel-community/eiffel-intelligence-frontend#165]
### Description
As a system tester I need to have a subscription for source change back-end so that this scenario can be tested

![sourcechangerules](https://user-images.githubusercontent.com/24456185/52562471-e6e19f80-2dfe-11e9-908e-171fe41c04de.png)

1. Subscription triggered by artifact object when only the SCS1 event have been created (see the diagram) it will trigger a job that sends an activity triggered event.
1. Subscription that triggers job sending activity started, activity finished, activity canceled
1. Subscription that triggers a job sending a confidence level modified when activity finished has been aggregated
1. Subscription that triggers a job that compares the aggregated object when the CLM event is aggregated. If this job pass then the test case passed

Part of #162

**Comment by e-pettersson-ericsson** [comment]
Since the code changes have been merged, I'll close this issue.
