### ISSUE TITLE
Source Change Jobs have Successfully Triggered

### ISSUE THREAD

**Issue by roos-ericsson** [eiffel-community/eiffel-intelligence-frontend#173]
### Description
As a system test designer I want to check that source change jobs have successfully triggered and then remove the subscriptions and jobs so that the system test environment is cleaned after the system tests. 

- [ ] Loop for some time to see source change jobs successfully triggered.
- [ ] Remove subscriptions and jobs.

Part of #162

**Comment by e-pettersson-ericsson** [comment]
I have a pull request open for this issue. #190

**Comment by e-pettersson-ericsson** [comment]
Since the code changes have been merged, I'll close this issue.
