### ISSUE TITLE
Need an easy way to copy and slightly modify the subscriptions.

### ISSUE THREAD

**Issue by evasiba-ericsson** [eiffel-community/eiffel-intelligence-frontend#188]
### Description
Need an easy way to copy and slightly modify the subscriptions. Add buttons to download a subscription as json and a button to upload the subscription from a json file.

### Motivation
Sometime user want to copy someone else subscription and just modify it slightly.

### Benefits
easy to get started with subscriptions.

**Comment by e-pettersson-ericsson** [comment]
Closing this issue since PR which adds this possibility has been merged.
