### ISSUE TITLE
User guide inconsistencies with actual GUI interface

### ISSUE THREAD

**Issue by lmcsega** [eiffel-community/eiffel-intelligence-frontend#75]
Some corrections needed in user guide,  I am working with EI in sandbox ver ei81.2

### Description

In section Rule testing mechanism via "Test Rules GUI inteface"
Title: missing the r in interface
First sentence (also missing the t in testing) reads "Graphical User interface for rule tesing consists from two panes"  should say "The graphical user interface for testing rules consists of two panes"

The image included  that shows the rules & events menu is not consistent with actual release GUI interface,  perhaps this needs updating?

**Comment by Christoffer-Cortes** [comment]
The image and grammar has been updated on the Test Rules wiki page.
